version: 2.1

orbs:
  aws-code-deploy: circleci/aws-code-deploy@2.0.0

executors:
  node-16:
    docker:
      - image: cimg/node:16.13.0
    working_directory: ~/project

workflows:
  version: 2
  deploy-api:
    jobs:
      - aws-code-deploy/deploy:
          application-name: 'ApiApplication'
          bundle-bucket: 'api-code-deploy-bucket-eu-west-1-261683817353'
          bundle-key: 'Production'
          deployment-group: 'ProductionApiDeploymentGroup'
          service-role-arn: 'arn:aws:iam::261683817353:role/CodeDeployServiceRole'
          filters:
            branches:
              only: main
