version: 2.1

orbs:
  aws-code-deploy: circleci/aws-code-deploy@3.0.0
  aws-cli: circleci/aws-cli@3.1.5

executors:
  node-16:
    docker:
      - image: cimg/node:16.19.1
    working_directory: ~/project

commands:
  restore:
    steps:
      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}
            - npm-
      - restore_cache:
          key: npm-cdk-{{ checksum "~/project/apps/infra/package-lock.json" }}

  save:
    steps:
      - save_cache:
          key: npm-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - save_cache:
          key: npm-cdk-{{ checksum "~/project/apps/infra/package-lock.json" }}
          paths:
            - apps/infra/node_modules

  aws_setup:
    parameters:
      role_arn:
        type: string
        description: Deploy role ARN
      profile:
        type: string
        description: Profile name for deploy role
    steps:
      - aws-cli/setup:
          profile-name: default
      - aws-cli/role-arn-setup:
          profile-name: << parameters.profile >>
          role-arn: << parameters.role_arn >>

jobs:
  tests:
    executor: node-16
    steps:
      - checkout
      - restore
      - run:
          name: Install Dependencies
          command: |
            npm install
      - save
      - run:
          name: Run Tests
          command: |
            npm test

  deploy-cdk:
    executor: node-16
    steps:
      - checkout
      - restore
      - run:
          name: Install cdk packages
          command: |
            cd apps/infra
            npm install -g aws-cdk
            npm install
      - save
      - aws_setup:
          role_arn: ${AWS_CDK_DEPLOY_ROLE_ARN}
          profile: cdk
      - run:
          name: Deploy Infrastructure
          command: |
            cd apps/infra
            cdk synth

            cdk deploy HidroStage/\* --require-approval never --profile cdk

  build-express-api:
    executor: node-16
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}
            - npm-
      - run:
          name: Build API
          command: npm run api:build
      - run:
          name: Copy additional artefacts
          command: |
            cp -r ~/project/scripts ~/project/dist
            cp ~/project/appspec.yml ~/project/dist
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist
  serverless-api:
    executor: node-16
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-{{ checksum "package-lock.json" }}
            - npm-
      - aws_setup:
          role_arn: "arn:aws:iam::261683817353:role/ProductionServerlessFrameworkDeploymentRole"
          profile: serverless
      - run:
          name: Deploy to AWS
          command: |
            export AWS_SDK_LOAD_CONFIG=1
            npm run api:sls:deploy -- --aws-profile serverless

workflows:
  version: 2
  build-and-test:
    jobs:
      - tests:
          filters:
            branches:
              ignore:
                - main
      - build-express-api:
          filters:
            branches:
              ignore:
                - main

  deploy-production:
    jobs:
      # Tests
      - tests:
          filters:
            branches:
              only: main

      # CDK
      - deploy-cdk:
          requires:
            - build-express-api

      # Express API
      - build-express-api:
          requires:
            - tests
      - aws-code-deploy/deploy:
          pre-steps:
            - attach_workspace:
                at: ~/tmp
          application-name: 'ApiApplication'
          bundle-bucket: 'api-code-deploy-bucket-eu-west-1-261683817353'
          bundle-key: 'Production'
          bundle-source: '../tmp/dist'
          deployment-group: 'ProductionApiDeploymentGroup'
          service-role-arn: 'arn:aws:iam::261683817353:role/CodeDeployServiceRole'
          auth:
            - aws_setup:
                role_arn: 'arn:aws:iam::261683817353:role/CodeDeployDeploymentRole'
                profile: 'code-deploy'
          profile-name: 'code-deploy'
          requires:
            - deploy-cdk
            - build-express-api

      # Serverless API
      - serverless-api:
          requires:
            - tests
