version: 2.1

orbs:
  aws-code-deploy: circleci/aws-code-deploy@3.0.0
  aws-cli: circleci/aws-cli@3.1.5

executors:
  node-16:
    docker:
      - image: cimg/node:16.19.1
    working_directory: ~/project

jobs:
  build-express-api:
    executor: node-16
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm ci
            npm i @nrwl/nx-linux-x64-gnu
      - run:
          name: Build API
          command: npm run api:build
      - run:
          name: Copy additional artefacts
          command: |
            cp -r ~/project/scripts ~/project/dist
            cp ~/project/appspec.yml ~/project/dist
      - persist_to_workspace:
          root: ~/tmp
          paths:
            - ../project/dist
  serverless-api:
    executor: node-16
    steps:
      - checkout
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
          name: Install Dependencies
          command: npm ci
      - run:
          name: Deploy to AWS
          command: npm run api:sls:deploy

workflows:
  version: 2
  deploy-production:
    jobs:
      # Express API
      - build-express-api:
          filters:
            branches:
              only: main
      - aws-code-deploy/deploy:
          pre-steps:
            - attach_workspace:
                at: ~/tmp/dist
          application-name: 'ApiApplication'
          bundle-bucket: 'api-code-deploy-bucket-eu-west-1-261683817353'
          bundle-key: 'Production'
          bundle-source: '~/project/dist'
          deployment-group: 'ProductionApiDeploymentGroup'
          service-role-arn: 'arn:aws:iam::261683817353:role/CodeDeployServiceRole'
          auth:
            - aws-cli/setup:
                aws-access-key-id: AWS_ACCESS_KEY_ID
                aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          filters:
            branches:
              only: main
          requires:
            - build-express-api

      # Serverless API
      - serverless-api:
          filters:
            branches:
              only: main
