service: hidro-api
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  deploymentMethod: direct
  stage: ${opt:stage, 'development'}
  runtime: nodejs18.x
  region: eu-west-1
  profile: ${env:AWS_PROFILE, 'default'}
  environment:
    SERVERLESS_STAGE: ${self:provider.stage, 'development'}

  iam:
    deploymentRole: arn:aws:iam::${aws:accountId}:role/ServerlessDeploymentRole

functions:
  hidro-api-post-data:
    handler: src/handler.handler
    memorySize: 256
    timeout: 5
    environment:
      DATABASE_HOST: ${env:DATABASE_HOST, ''}
      DATABASE_SECRET_NAME: ${env:DATABASE_SECRET_NAME, ''}
    events:
      - httpApi:
          path: /Post-dataHE.php
          method: post


custom:
  deploymentRole:
    local: ''
    staging: ''
    production: ''
