service: hidro-api
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-offline
  - serverless-bundle

provider:
  name: aws
  deploymentMethod: direct
  stage: ${opt:stage, 'development'}
  runtime: nodejs16.x
  region: eu-west-1
  profile: ${env:AWS_PROFILE, 'default'}
  environment:
    SERVERLESS_STAGE: ${self:provider.stage, 'development'}

  iam:
    deploymentRole: arn:aws:iam::${aws:accountId}:role/${self:custom.deploymentRole.${opt:stage, 'local'}}
    role:
      statements:
        - Effect: Allow
          Action:
            - ssm:GetParameter
            - ssm:GetParameters
            - ssm:GetParametersByPath
          Resource:
            - 'arn:aws:ssm:*:*:parameter/techvindesta/rds/**/*'
            - 'arn:aws:ssm:*:*:parameter/techvindesta/rds/*'
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource:
            - 'arn:aws:secretsmanager:eu-west-1:261683817353:secret:rds!db-80899538-9b2f-4f06-98da-7b6b0c97b4c2-2rNBmK'

functions:
  he-post-data:
    handler: src/post-data.handler
    memorySize: 256
    timeout: 10
    environment:
      DATABASE_SECRET_NAME: ${env:DATABASE_SECRET_NAME, ''}
    events:
      - httpApi:
          path: /Post-dataHE.php
          method: post

  he-get-data:
    handler: src/get-data.handler
    memorySize: 256
    timeout: 30
    environment:
      DATABASE_SECRET_NAME: ${env:DATABASE_SECRET_NAME, ''}
    events:
      - httpApi:
          path: /he-data/{name}
          method: get


custom:
  deploymentRole:
    local: ''
    staging: ''
    production: 'ProductionServerlessFrameworkDeploymentRole'

  bundle:
    linting: false
    minifyOptions:
      keepNames: true
