service: hidro-api

frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1

functions:
  hidro-api-post-data:
    handler: src/handler.handler
    events:
      - http:
          path: /Post-dataHE.php
          method: post
